config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
    resources :cart_itens, only: [:create, :update, :destroy]
  end
 
  unauthenticated :user do
    root to: "home#index"
  end
  resources :brands, only: [:index, :show]
  resources :search, only: [:index], as: :searches
  
  get "/cart", to: "cart#index", as: :cart
  get "/address", to: "address#index", as: :address
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
  has_one_attached :cover
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_many :brands, through: :products
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favoritable, polymorphic: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :category

  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/address_controller.rb
class AddressController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    # load_recent_heard
    # load_recommendations
  end


  private


  def load_recent_heard
    @recent_albums = current_user.recently_heards.order("created_at DESC").limit(4).map(&:album)
  end


  def load_recommendations
    heard_categories = @recent_albums.map(&:category)
    @recommended_albums = Album.joins(:category, :songs).where(category: heard_categories).order("songs.played_count")
                               .select("distinct albums.*").limit(4)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @brands = Brand.limit(4)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/address/index.html.erb
<section class="hero is-dark">
  <div class="hero-body has-text-centered">
    <h1>Contatos</h1>
  </div>
</section>

app/views/cart/index.html.erb
<section class="hero is-dark">
  <div class="hero-body has-text-centered">
    <h1>Carrinho de compras</h1>
  </div>
</section>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/home/index.html.erb
<section class="hero is-dark">
  <div class="hero-body has-text-centered">
    <div class="container">
      <div class="is-2-desktop">
          <%= image_tag "logo.png" %>
      </div>
      <h1 class="title has-text-weight-light">
        AQUI VOCÊ VAI <br />
        <span class="has-text-primary">SE REALIZAR</span>
      </h1>
      <div class="columns is-mobile is-multiline">
        <% @brands.each do |brand| %>
          <div class="column is-half">
            <%= link_to brand, class: 'is-small has-background-white-ter is-rounded is-fullwidth button has-text-primary' do %>
              <span class="icon">
                <i class="fa fa-chevron-circle-right"></i>
              </span>
              <span><%= brand.name %></span>
            <% end %>
          </div>
        <% end %>
      </div>
      <br /><br />
      <%= link_to "CADASTRE-SE!!", new_user_registration_path, class: "button is-medium is-outlined is-primary" %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top has-background-dark">
  <head>
    <title>Filó Lingerie</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="has-background-dark">
    <%= render "shared/menu" %>
    <%= yield %>
    <%= render "shared/toolbar" %>
  </body>
</html>

app/views/search/index.html.erb
<section class="hero is-dark">
  <div class="hero-body has-text-centered">
    <h1>Resultado de busca</h1>
  </div>
</section>

app/views/shared/_menu.html.erb
<nav class="columns is-mobile is-dark navbar is-fixed-top">
  <% unless current_page?(root_path) %>
  <div class="column is-2-desktop logo">
      <%= link_to image_tag("logo.png"), root_path %>
  </div>
  <% end %>

  <div class="column menu-button">
    <% if user_signed_in? %>
      <div class="dropdown is-hoverable is-pulled-right is-right">
        <div class="dropdown-trigger">
          <a class="icon is-large" aria-haspopup="true" aria-controls="dropdown-menu">
            <i class="fas fa-cog fa-2x has-text-white-bis"></i>
          </a>
        </div>
        <div class="dropdown-menu" id="dropdown-menu" role="menu">
          <div class="dropdown-content">
            <%= link_to "Sua Conta", edit_user_registration_path, class: "dropdown-item" %>
            <hr class="dropdown-divider">
            <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
      </div>
    <% else %>
      <%= link_to "ENTRAR", new_user_session_path, class: "button is-pulled-right is-outlined is-white" %>          
    <% end %>
  </div>
</nav>

app/views/shared/_toolbar.html.erb
<nav class="columns is-mobile is-dark navbar is-fixed-bottom toolbar">
  <div class="column has-text-centered">
    <%= link_to root_path, class: "has-text-white" do %>
      <i class="fa fa-home fa-lg"></i>
    <% end %>
  </div>

  <div class="column has-text-centered">
    <%= link_to searches_path, class: "has-text-white" do %>
      <i class="fa fa-search fa-lg"></i>
    <% end %>
  </div>

  <div class="column has-text-centered">
    <%= link_to cart_path, class: "has-text-white" do %>
      <i class="fas fa-cart-plus fa-lg"></i>
    <% end %>
  </div>
  
  <div class="column has-text-centered">
    <%= link_to address_path, class: "has-text-white" do %>
      <i class="fas fa-address-book fa-lg"></i>
    <% end %>
  </div>
</nav>